### ISSUE TITLE
decide on keeping or removing service-meta link relation in -06 draft

### ISSUE THREAD

**Issue by dret** [dret/I-D#101]
check with @mamund to see whether the `service-meta` link relation should be kept or removed. it was meant to complement the others for a more general-purpose service metadata format, but it may be too aspirational for now.

**Comment by mamund** [comment]
i rather like the `service-meta` link since it offers a kind of "third option" from the human doc (`service-doc`) and machine doc (`service-desc`) options.

here are some things i think might be good examples of content for the `service-meta` link-rel value:

 * json schema and/or hyper-schema document (http://json-schema.org/)
 * HAL-FORMS document (https://rwcbook.github.io/hal-forms/)
 * JSON-LD (applied to an existing JSON document)

**Comment by dret** [comment]
On Jul 24, 2018, at 21:19, Mike Amundsen <notifications@github.com> wrote:
> i rather like the service-meta link since it offers a kind of "third option" from the human doc (service-doc) and machine doc (service-desc) options.
> 
> here are some things i think might be good examples of content for the service-meta link-rel value:
> 
> json schema and/or hyper-schema document (http://json-schema.org/)
> HAL-FORMS document (https://rwcbook.github.io/hal-forms/)
> JSON-LD (applied to an existing JSON document)

ok. would it help or even be appropriate to add some language that for something as wide-ranging as `service-meta` it might be a good idea to use it with some kind of link hint?

**Comment by mamund** [comment]
link hint? as in HTML `type="application/alps+json"` or something else?

**Comment by dret** [comment]
https://tools.ietf.org/html/draft-wilde-service-link-rel-06 is published now, please feel free to review the minor addition in terms of mentioning the link hint idea. if that's fine, i am assuming we can close this issue.

**Comment by mamund** [comment]
looks fine -- you can close this one out, too.
