### ISSUE TITLE
content-warning: should we tie it to the http status code?

### ISSUE THREAD

**Issue by ioggstream** [dret/I-D#135]
## Note

The spec says

> the response status code SHOULD be in the 2xx range

Q: do we need to tie this header to the http status code?

**Comment by andrecedik** [comment]
Well, as you pointed out, we're saying that the response could should be in the 2xx range. This is due to the fact, that the original intent was successful, but unfortunately something (else) also happened that the agent should know about. So the request actually was successful - it just has side conditions. 

I've added a side note with [this commit](https://github.com/dret/I-D/commit/c0f46c4f441dcc6dd6af70a8287adfc32c6dc830). To make this clearer.
