### ISSUE TITLE
Double check the @id for hreflang in the example JSON-LD context

### ISSUE THREAD

**Issue by dret** [dret/I-D#140]
( couldn't assign this issue to @stain, so assigned it to myself instead... )
the JSON-LD context in https://tools.ietf.org/html/draft-wilde-linkset-06#appendix-B currently uses `https://www.w3.org/ns/activitystreams#hreflang` as the `@id` for `hreflang`, but uses DC terms for most other concepts. is there a reason to refer to the activity streams vocabulary for just this one concept, instead of using DC like for all other concepts?

**Comment by stain** [comment]
I think @hvdsomp found that - I guess because `hreflang` is a direct match for the Linkset meaning. Dublin Core Terms would have [dct:language](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/language) which is also appropriate - I am fine with changing it if you think it makes it simpler with a single vocabulary.

An alternative mapping to schema.org <https://schema.org/LinkRole> would use <https://schema.org/inLanguage>

**Comment by dret** [comment]
On 2020-06-26 11:04, Stian Soiland-Reyes wrote:
> I think @hvdsomp <https://github.com/hvdsomp> found that - I guess 
> because |hreflang| is a direct match for the Linkset meaning. Dublin 
> Core Terms would have dct:language 
> <https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/language> 
> which is also appropriate - I am fine with changing it if you think it 
> makes it simpler with a single vocabulary.

it was actually @philarcher pointing it out when we recently talked 
about GS1's plans to start using linksets.

> An alternative mapping to schema.org https://schema.org/LinkRole would 
> use https://schema.org/inLanguage

i guess ideally you rely on as few vocabularies as possible, no? if so, 
maybe the DC term would be the best choice?

**Comment by hvdsomp** [comment]
Hey @stain, I don't think it was me but I am going to assume it was @csarven who suggested `https://www.w3.org/ns/activitystreams#hreflang` as the `@id` for `hreflang`. I am sure it's a correct approach, but - as @dret indicates - it's probably better to use as few (widely known) vocabularies as possible, especially since this is for an example context provided FYI in an Appendix. So, I would definitely be in favor of using dct:language.

**Comment by dret** [comment]
On 2020-06-29 08:35, Herbert Van de Sompel wrote:
> Hey @stain <https://github.com/stain>, I don't think it was me but I am 
> going to assume it was @csarven <https://github.com/csarven> who 
> suggested |https://www.w3.org/ns/activitystreams#hreflang| as the |@id| 
> for |hreflang|. I am sure it's a correct approach, but - as @dret 
> <https://github.com/dret> indicates - it's probably better to use as few 
> (widely known) vocabularies as possible, especially since this is for an 
> example context provided FYI in an Appendix. So, I would definitely be 
> in favor of using dct:language.

out of curiosity i checked 
https://www.w3.org/ns/activitystreams#hreflang on sameas.org but nothing 
shows up. but then again, the whole exercise of deciding "when are two 
concepts really the same" is a bit of an ontological snake pit to begin 
with....

**Comment by larsgsvensson** [comment]
> out of curiosity i checked
https://www.w3.org/ns/activitystreams#hreflang on sameas.org but nothing
shows up. but then again, the whole exercise of deciding "when are two
concepts really the same" is a bit of an ontological snake pit to begin
with....

Slightly OT: Since [as:hreflang](https://www.w3.org/ns/activitystreams#hreflang)  and [dct:language](http://purl.org/dc/terms/language) are different individuals, they should not be `owl:sameAs`-ed anyway...

**Comment by dret** [comment]
On 2020-06-29 09:44, Lars G. Svensson wrote:
> Slightly OT: Since as:hreflang 
> <https://www.w3.org/ns/activitystreams#hreflang> and dct:language 
> <http://purl.org/dc/terms/language> are different individuals, they 
> should not be |owl:sameAs|-ed anyway...

i guess i looked in the wrong place. same as is for "real identity" and 
not for "just equality", i assume. whatever differentiates these (hence 
the ontological snake pit remark)...

**Comment by csarven** [comment]
Background: https://github.com/dret/I-D/issues/89#issuecomment-461192217 :)

Yes, using dcterms:language instead works.

**Comment by philarcher** [comment]
Sorry - should have jumped in last week. Yes, we (GS1) thought dcterms:language made sense for all the reasons discussed here. I'm tempted by schema:inLanguage (my rule of thumb - if it's in schema.org and the relatively loose semantics don't kill you, use it) but, well, we're looking at DC for most of this. Hmm... the tyranny of choice.

**Comment by hvdsomp** [comment]
Used the DC Terms URI for language in JSON-LD context.
