### ISSUE TITLE
Context must be included, and must be defined as immutable

### ISSUE THREAD

**Issue by dret** [dret/I-D#21]
the current draft just mentions the context by reference and then includes it as "informative section" at the very end. it seems to me that the context is at the very heart of the spec: it is what really defines how JSON and RDF are mapped.
i am not convinced that having a normative URI even is such a good idea anyway. after all, if we imagine this being hugely successful, wouldn't that cause enormous load at that single URI? and isn't the important thing that the spec defines the mapping itself, and not so much some URI where it may (or may not, if this shuts down for some reason) be available?
i'd imagine most business applications would use the context by value (and not by reference) anyhow, because reducing dependencies (in particular on resources not under your control) always is a smart thing to do. what we would need to do at the very least would be to clearly say that the context definition will never ever change, so that using it by value would be a safe thing to do.

**Comment by dret** [comment]
on second thought: isn't it true that JSON-LD cannot work without an explicit context with a resolving URI? or is it legal to have a non-HTTP URI that just identifies the context, but doesn't serve it?

**Comment by asbjornu** [comment]
I'm not fluent enough in JSON-LD to answer this, but I hope @RubenVerborgh, @lanthaler, @dschulten, or @elf-pavlik knows?

**Comment by dret** [comment]
http://www.markbaker.ca/blog/2016/02/note-on-state-and-self-description/ is the result of a discussion that started on twitter, and ended in mark writing his blog post. it's a good (and short) read for this issue.

**Comment by elf-pavlik** [comment]
> isn't it true that JSON-LD cannot work without an explicit context with a resolving URI?

JSON-LD has various profiles, [Expanded Document Form](https://www.w3.org/TR/json-ld/#expanded-document-form) doesn't use context. If one wants to use [Compacted Document Form](https://www.w3.org/TR/json-ld/#compacted-document-form) and not depend on external context, than using local context inline can work.

>Contexts can either be directly embedded into the document or be referenced.
 &mdash; https://www.w3.org/TR/json-ld/#the-context

To stay honest I miss context for this issue, what JSON-LD context do we discuss? (hyperlink please)

**Comment by dschulten** [comment]
Here is the context we are talking about:
https://github.com/dret/I-D/blob/master/http-problem-rdf/http-problem-context.jsonld

The context would be stable for http-problem in the current version of the rfc, and we could strongly suggest to embed it for stability and performance reasons. However, so far it seems customary to provide an external context, too - e.g. schema.org or hydra do it. Making it "aggressively" cacheable is essential.

The json-ld playground fails if an external context is not dereferenceable. So it is definitely not the idea that the context is not dereferenceable.

**Comment by asbjornu** [comment]
I think it is a valid point that the context can be embedded. Interoperability and performance (due to it being cached) would be better if the context is external, but I don't see it as a requirement. However, if it is made external, it needs to be dereferenceable and of course as already mentioned "aggressively" cacheable.

Speaking of which, I just came to think of that back in the day, W3 was having issues with the HTML DTD being aggressively downloaded by everyone and their dog until someone realized that the URI was static, would never change and could in effect be baked into the browser or DOM environment. I don't remember the details, but I believe they are roughly correct and very analogous to what we're discussing here.

**Comment by dret** [comment]
On 2016-02-17 23:17, Asbjørn Ulsberg wrote:
> I think it is a valid point that the context can be embedded.
> Interoperability and performance (due to it being cached) would be
> better if the context is external, but I don't see it as a requirement.
> However, if it is made external, it needs to be dereferenceable and of
> course as already mentioned "aggressively" cacheable.

too bad that we cannot make this truly self-contained without including 
the entire mapping by value. if we do that, the assumption is that these 
highly redundant contexts will be shipped with every response and people 
will assume that they are an exact copy of the normative context?

> Speaking of which, I just came to think of that back in the day, W3 was
> having issues with the HTML DTD being aggressively downloaded by
> everyone and their dog until someone realized that the URI was static,
> would never change and could in effect be baked into the browser or DOM
> environment. I don't remember the details, but I believe they are
> roughly correct and very analogous to what we're discussing here.

yes, exactly. that anecdote was part of the twitter conversation, and 
should be read as a cautionary tale. using dereferencable identifiers 
when you don't have to (because what you really want is stable resource 
semantics signaled by the identifier) is risky, and has zero benefits.

**Comment by dret** [comment]
On 2016-02-17 19:45, Dietrich Schulten wrote:
> The json-ld playground fails if an external context is not
> dereferenceable. So it is definitely not the idea that the context is
> not dereferenceable.

yes, that's the underlying problem. no by-reference semantics at all, 
all you can get is by-value. bad for standards!

**Comment by dret** [comment]
On 2016-02-17 18:58, elf Pavlik wrote:
> To stay honest I miss context for this issue, what JSON-LD context do we
> discuss? (hyperlink please)

the general question was as follows (and the specific context is of no 
consequence): if a standards sets a context, is there a way how to refer 
to this by-reference, instead of by-value? i.e., can i use a 
non-referencable URI to identify the standard that i want to refer to, 
without having to host a (potentially critically overloaded) 
referencable context that simply repeats what the standard says? the 
answer seems to be that this is not possible.

**Comment by lanthaler** [comment]
As always, it is a trade-off. That being said, `@vocab` is very helpful in situations in which you don't want to reference a context and keep the embedded context small.

Given that people can mix and match vocabularies as they seem them fit and the fact that vocabularies typically evolve, it is, IMO unrealistic to expect that generic clients will hard-code contexts.

**Comment by dret** [comment]
@lanthaler, "vocabularies typically evolve" is probably true when you look at the entirety of vocabularies that people use. however, with standards it's almost always the opposite. the idea of a standard hinges on the fact that it is a fixed and agreed-on vocabulary that you can identify by reference (simply by saying "i am using standard X").
if standards do evolve, then there's a typical pattern how to do this by separating the fixed part into the stable standard itself, and the evolving part into a registry (https://tools.ietf.org/html/draft-wilde-registries). however, even in this case the assumption usually is that it's safe to rely on a snapshot of the registry, and that it's neither necessary nor the typical usage pattern to update that snapshot at runtime.

**Comment by asbjornu** [comment]
@dret (from mnot/I-D#144):
> i still think that in most cases, the general model is that runtime access is a Bad Idea, and for whoever is hosting the registry, this can make a big difference. definitely something to keep in mind when considering how to split a spec into static and evolvable parts.

I agree, but that comes down to (a bad) client implementation practice and not something that should guide the design of the hypermedia architecture too much, imho. 

> using dereferencable identifiers when you don't have to (because what you really want is stable resource semantics signaled by the identifier) is risky, and has zero benefits.

I disagree. The dereferencability of the identifiers make them self descriptive. If the format presented at the end of the dereferencable URI is a well-designed HTML document, it will help implementers immensely in understanding what the identifier is and how it's supposed to be used. This will in turn increase adoption and make the best documented and most accessible (human readable) identifiers more known and over time establish a de facto standard for which identifiers to use when identifying concept X. The fewer identifiers in use describing the same concept, the better.

If you remove the dereferencability part of the equation, the identifier becomes much more obscure, which will hurt adoption and lead to fragmentation. That obscurity leads to fragmentation is partly proven by the current situation in the hypermedia slash registry community where because the IANA and IETF process is so archaic and obscure, "everyone" seek other solutions (like wikis) to establish registries instead of using IANA.

I think the advice @gkellogg provded in mnot/I-D#144 is good:

> I believe the best practice for an implementation is to cache retrieved contexts and reuse between successive requests. Ideally, the context is served with reasonable cache control directives.

This practice can be prescribed and encouraged by the specification that defines the context URI. Not that it will fix all problems, but the W3C HTML DTD anecdote mentioned earlier is after all not a problem anymore. So good information and communication around this will help and is a better solution to the problem than not making the URI dereferencable in fear and protection against bad client implementations.
