### ISSUE TITLE
Relation to "Out-of-band Reporting"

### ISSUE THREAD

**Issue by dret** [dret/I-D#22]
https://github.com/mikewest/error-reporting defines an HTTP header field (`Report-To`) for a URI for reporting. https://github.com/mikewest/error-reporting/issues/5 asks is there is any relation between this header field, and the proposed `issues` link relation type.

**Comment by npdoty** [comment]
I think the `issues` link rel is different in two key ways: 1) user-initiated reports rather than reports from site JavaScript or from violations of rules set by the site; 2) reports provided interactively by the user as opposed to background asynchronous communication.

However, using a header/domain approach does have the advantage of providing an endpoint that a user agent can cache for reporting a certain class of problems wherever on the domain they occur.

**Comment by asbjornu** [comment]
Even though they are different, I think they are so closely related that they should try to agree on some over-arching semantics, naming and stuff like that to avoid confusion between the two concepts.

**Comment by dret** [comment]
closing because the draft got dropped a long time ago.
