### ISSUE TITLE
describedBy and service-desc interaction unclear

### ISSUE THREAD

**Issue by serialseb** [dret/I-D#31]
Introducing new relation types can cause significant fragmentation and difficulties to developers implementing those relationships.

describedBy has been registered by POWDER (in http://www.w3.org/TR/powder-dr/#appD), and the iana registration is pretty relaxed. There was a similar conversation on json-ld at https://github.com/json-ld/json-ld.org/issues/197 which may be of interest, which would point for a more general format to be heading the way of describedBy.

Is there a reason why the service document relation type cannot leverage describedBy combined with type param to deduct description formats?

**Comment by dret** [comment]
> describedBy has been registered by POWDER (in
> http://www.w3.org/TR/powder-dr/#appD), and the iana registration is
> pretty relaxed. There was a similar conversation on json-ld at
> json-ld/json-ld.org#197
> <https://github.com/json-ld/json-ld.org/issues/197> which may be of
> interest, which would point for a more general format to be heading the
> way of describedBy.

good link. @cygri's initial comment summarizes describedBy like this 
(and as i think, very accurately):

"The semantics of describedby relation type, as defined by POWDER and 
registered with IANA, is to link to a POWDER document that describes the 
subject resource, in other words, provides metadata about it."

> Is there a reason why the service document relation type cannot leverage
> describedBy combined with type param to deduct description formats?

if you interact with a resource, then there's a big difference between 
the resource itself (let's say a book, and then a description of that 
book would be metadata such as publication info), and the service that 
may be available for it (such as a service that allows you to submit 
annotations, or buy it, or whatever the service context of the resource is).

so from my perspective, POWDER is a distinct model that is only 
concerned with describing the resource, not the service context for it.

**Comment by serialseb** [comment]
My point was that, since teh errata in https://www.w3.org/2007/powder/powder-errata#describedby, there is no such assocaition between describedBy and POWDER, aka describedBy is for any description of a resource as per IANA registration. I find the proliferation of rel types for service description, be it json-ld, powder describedBy, this ID and service in atom to be rather alarming.

That said, if I understand you correctly, the idea here is to have a relation type that allows all resources part of an "API" to have a common identifier describing said API? Or a resolvable document describing said API? If it's the latter, how does it differ from a json-ld context in what used to be describedBy, a POWDER document, or the rel=service in atom?

**Comment by dret** [comment]
On 2016-02-22 12:01, Sebastien Lambla wrote:
> My point was that, since teh errata in
> https://www.w3.org/2007/powder/powder-errata#describedby, there is no
> such assocaition between describedBy and POWDER, aka describedBy is for
> any description of a resource as per IANA registration. I find the
> proliferation of rel types for service description, be it json-ld,
> powder describedBy, this ID and service in atom to be rather alarming.

i think now we're getting into a meta-discussion. i have skimmed the 
thread and found it informative in terms of not ending with a conclusion 
to the general dilemma.

i find the general dilemma to be (and that's my personal view of that 
thread) that having an unlimited general-purpose describedBy relation 
serves little purpose. it just means "there's something related over 
there". for that, no link relation type is required, imho, you can just 
use an unqualified link.

from the hypermedia/REST pov, the idea of link relations is to allow 
clients to decide where the application flow should go. that's what this 
draft is trying to accomplish.

in the end, the exact semantics of a typed link are determined by 
context. if one API links from resources to service descriptions using 
"describedBy", that works. if another one uses "service-doc/desc", that 
also works. if a third one uses 
"http://example.com/ourrelation/services", that works as well.

the draft proposes a very small "vocabulary" to be used by APIs so that 
they don't have to invent one. striking the balance of generalization of 
specialization is a matter of preference. if people are looking for 
something reusable that is based on the assumption that link relation 
types should be something meaningful, then this draft hopefully looks 
useful to them. if they don't like this balance, then they'll move on.

> That said, if I understand you correctly, the idea here is to have a
> relation type that allows all resources part of an "API" to have a
> common identifier describing said API? Or a resolvable document
> describing said API? If it's the latter, how does it differ from a
> json-ld context in what used to be describedBy, a POWDER document, or
> the rel=service in atom?

well, a resource may not even know it's "part of an API", that context 
may be provided externally by a 3rd party ("i know this resource can be 
bought over there, and here's the description of the service that allows 
you to purchase this resource"). if the resource knows it's part of an 
API and exposes this knowledge as a link, then i think one API design i 
would consider would be to link from that resource to the "home" resource:

https://github.com/mnot/I-D/issues/41

from that home resource, i'd make service descriptions available in 
human- or machine-readable form, using this draft's link relations. but 
that's just my design preference; other service designers might choose 
to make links available in a different configuration.

**Comment by serialseb** [comment]
That makes sense. Is the hope that future media type registrations will avoid registering yet another relation type for what is a document describing a service in a machine readable format? Would this ID have made service/describedBy/json-ld#context redundant, or at least less required?

**Comment by dret** [comment]
On 2016-02-22 12:23, Sebastien Lambla wrote:
> That makes sense. Is the hope that future media type registrations will
> avoid registering yet another relation type for what is a document
> describing a service in a machine readable format?

yes, you could say that. if you were designing a hypermedia service and 
as part of it, you wanted to provide links to service documentation 
and/or description, then hopefully you'd use these registered relations 
and would not mint your own ones.

> Would this ID have
> made service/describedBy/json-ld#context redundant, or at least less
> required?

i guess "service" still makes sense if you have a mixed service 
documentation/description format. but then you could also have two links 
to the same resource. it boils down to whether you find it helpful, from 
the hypermedia pov, to provide distinct links.

"describedBy" in it's  very general form is strange because it subsumes 
everything. in it's more limited form ("identifies a link to a target 
resource providing a description of the source resource"), i could 
easily see those two being combined: find a resource, follow 
"describedBy" to get metadata about it, and then find a 
"service-documentation" link in that metadata that allows you to read 
documentation about a service context for the original resource.

"json-ld#context" is very specific and thus pretty unrelated. it's a 
very "mechanical" link that provides access to data mapping info, so to 
me it's less a "hypermedia" link and more one that's on the data model 
and data mapping/transformation level of things.

**Comment by pmhsfelix** [comment]
IMO, at first sight there seems to be a significant overlap between `describedBy`, `service` and `service-desc`. I think I understand @dret arguments about the description scope (`describedBy` for specific resource metadata vs. `service-desc` for a "wider" service description). However, do we really need to have distinct relations for them? Can't the distinction be made by the target resource representation (both type and contents)? 
Adding `service` to mix only makes things less straighforward. 
Namely, aren't we coupling the `describedBy` and `service` to specific target types (POWDER and ATOM), when the rels should be more target type agnostic?
At least the document should include a section describing where `service-desc` differs and complements `describedBy` and `service`.

**Comment by dret** [comment]
On 2016-02-22 23:55, Pedro Felix wrote:
> IMO, at first sight there seems to be a significant overlap between
> |describedBy|, |service| and |service-desc|. I think I understand @dret
> arguments about the description scope
> (|describedBy| for specific resource metadata vs. |service-desc| for a
> "wider" service description). However, do we really need to have
> distinct relations for them? Can't the distinction be made by the target
> resource representation (both type and contents)?

this is a rather fundamental design philosophy question, so we shouldn't 
try to solve it here. from a hypermedia/REST perspective, the link 
itself should allow a client to decide whether it wants to follow that 
path or not. in order for this to work, the link itself needs to be 
expressive enough to understand why you would or wouldn't want to follow it.

i do understand that this is not a world view that's shared by everyone. 
but that's the reason for the specific design, and for the goal to make 
link relation types specific enough to allow a client to make this decision.

more specifically, i don't think that |service-desc| is for a "wider 
service description" than |describedBy|. it's for something 
categorically different.

> Namely, aren't we coupling the |describedBy| and |service| to specific
> target types (POWDER and ATOM), when the rels should be more target type
> agnostic?

they should be, and they are. per their IANA registration, there are no 
assumptions about the target resource's media type. that's almost 
required, because even though the guidelines for registering link 
relation types may be relatively vague, there is one that clearly states 
that you cannot hardcode assumptions about the target resource's media type:

http://tools.ietf.org/html/rfc5988#section-4.1 (third paragraph)

> At least the document should include a section describing where
> |service-desc| differs and complements |describedBy| and |service|.

i disagree about |describedBy|, because that's a different beast 
altogether. i agree that |service| should be mentioned: #33

**Comment by asbjornu** [comment]
In my humble opinion, minting different relation types for every different expected media type at the end of the URI does not scale and is not how most of the existing relations works. If it's important to indicate what media type one can expect to find at the related URI, most markup languages and formats have a `type` concept in which you can provide a MIME type.

And if it's impossible to be declarative about the MIME type of the related URI, you have content negotiation. The client can tell the server which format it will `Accept` and the server can either provide that format or respond with `406 Not Acceptable`.

Either way, I think this duality between relation type and media type is how most relations already work and that those who doesn't work in this way are needlessly narrow in their definition and should rather be opened up than set a precedent for future relation types to also be narrow and inflexible.

**Comment by asbjornu** [comment]
> Registered relation types MUST NOT constrain the media type of the context IRI, and MUST NOT constrain the available representation media types of the target IRI.  However, they can specify the behaviours and properties of the target resource (e.g., allowable HTTP methods, request and response media types that must be supported).

I think [the above section](http://tools.ietf.org/html/rfc5988#section-4.1) is pretty clear on **not** coupling relation type with media type? What am I misunderstanding here?

**Comment by dret** [comment]
On 2016-02-24 08:00, Asbjørn Ulsberg wrote:
> In my humble opinion, minting different relation types for every
> different expected media type at the end of the URI does not scale and
> is not how most of the existing relations works. If it's important to
> indicate what media type one can expect to find at the related URI, most
> markup languages and formats have a |type| concept in which you can
> provide a MIME type.

i don't think there's any disagreement on that. and RFC 5988 
specifically disallows this kind of tight coupling anyway. here's some 
framework that tries to separate those issues:

https://github.com/dret/hyperpedia/blob/master/concepts.md#link-relation-type

https://github.com/dret/hyperpedia/blob/master/concepts.md#target-resource-hints

> Either way, I think this duality between relation type and media type is
> how most relations already work and that those who doesn't work in this
> way are needlessly narrow in their definition and should rather be
> opened up than set a precedent for future relation types to also be
> narrow and inflexible.

i am not sure what you are referring to. nobody (afaict for the context 
of this thread) wants to constrain a link relation type to a specific 
media type. and as mentioned above, it is not even allowed for 
registered types.

**Comment by serialseb** [comment]
So it comes to this: what is the difference between describedBy "here's some resource describing this resource" and service-desc "here's some resource describing the api in use in a machine readable fashion".
Let's ask this slightly differently: what are the cases where the resource describing a resource and the resource describing the set of resources a resource is part of (the api) are different? Also useful would be, what are the cases where each of those concepts ought to be different because they may be used at the same time?
Maybe that would clarify things in the specification.

**Comment by dret** [comment]
On 2016-02-24 11:50, Sebastien Lambla wrote:
> So it comes to this: what is the difference between describedBy "here's
> some resource describing this resource" and service-desc "here's some
> resource describing the api in use in a machine readable fashion".

the first one is a link to metadata about the resource.

the second one is a link to description/documentation (which you could 
see as "metadata", but i think that's more confusing than helpful) of 
something else: of a service that provides access to the resource (and 
likely many others as well).

> Let's ask this slightly differently: what are the cases where the
> resource describing a resource and the resource describing the set of
> resources a resource is part of (the api) are different?

the api is not "describing the set of resources". it describes/documents 
the rules of engagement with that set.

> Also useful
> would be, what are the cases where each of those concepts ought to be
> different because they may be used at the same time?

they ought to be different in every single case, because they are 
different things.

i said it before, but maybe not in this thread: if you approach things 
from the angle that *any* descriptive approach for *anything* should be 
covered by describedBy, you have generalized the concept so much that it 
uses all utility and you might as well skip link types altogether.

if i find a book resource and would like to find metadata (typical data 
such as publication metadata) about the book resource, then i'd follow 
describedBy.

if i have other needs, i'll follow other links. one of those needs might 
be that there is a service that provides access to the book. if i am 
interested in that service, i'll find out more about it via 
service-desc/doc.

that being said, nobody can keep you from subsuming everything under 
describedBy. personally, i would not find that a great design, as it 
would not help hypermedia clients to follow links based on their 
application goals. but you might think otherwise and then you'd do 
everything with describedBy and things would work as well, just slightly 
differently.

**Comment by serialseb** [comment]
Let me say that I'm only arguing here in the name of moving the description in the spec to resolve those questions upfront, not for the sake of argument or because i argue everything should be describedBy.

I think things are not as clear cut because of two concommitent things: the former use of describedBy in json-ld and the fact that the metadata about the resource in json-ld+hydra now describes the rule of engagement for a resource and its linked resources, making the whole thing fairly fuzzy and without clear distinction, for example http://www.hydra-cg.com/spec/latest/core/#discovering-a-hydra-powered-web-api

**Comment by dret** [comment]
On 2016-02-24 12:21, Sebastien Lambla wrote:
> I think things are not as clear cut because of two concommitent things:
> the former use of describedBy in json-ld and the fact that the metadata
> about the resource in json-ld+hydra now describes the rule of engagement
> for a resource and its linked resources, making the whole thing fairly
> fuzzy and without clear distinction, for example
> http://www.hydra-cg.com/spec/latest/core/#discovering-a-hydra-powered-web-api

this looks as if hydra currently uses it's own link relation type for 
the exact same purpose. that's fine. they do not use describedBy, so 
wouldn't that be a data point in favor of having a more specific link 
relation that describedBy? they could switch to `service-description` 
(or the already existing `service`), in which case "service crawlers" 
would have an easier time understanding which resources were made 
available through which services.

also, iirc, JSON-LD did not use describedBy and also ended up with 
minting its own link relation type (but that's a different kind of 
relation, if you refer to how to link to a context).

**Comment by asbjornu** [comment]
Sorry for having added confusion to the discussion, but after reading what's been written since my comments, I think everything is now much clearer. At least to me, anyway. I hope that will help other understand what's actually being discussed here. Below is a summary.

**describedBy:**
> here's some resource describing this resource" and service-desc "here's some  resource describing the api in use in a machine readable fashion". the first one is a link to metadata about the resource.

**service-desc:**
> a link to description/documentation of a service that provides access to the resource (and likely many others as well).

I agree that these are two separate concepts. So, on to the proposed `service-desc` and `service-doc` relations; what's differing these from RFC 5023's `service` relation?

**Comment by dret** [comment]
On 2016-02-24 13:08, Asbjørn Ulsberg wrote:
> Sorry for having added confusion to the discussion, but after reading
> what's been written since my comments, I think everything is now much
> clearer. At least to me, anyway. I hope that will help other understand
> what's actually being discussed here. Below is a summary.
>
> *describedBy:*
>     here's some resource describing this resource" and service-desc
>     "here's some resource describing the api in use in a machine
>     readable fashion". the first one is a link to metadata about the
>     resource.
>
> *service-desc:*
>     a link to description/documentation of a service that provides
>     access to the resource (and likely many others as well).

and thanks for the summary, that's probably helpful.

> I agree that these are two separate concepts. So, on to the proposed
> |service-desc| and |service-doc| relations; what's differing these from
> RFC 5023's |service| relation?

nothing really other than the ability to separate human- and 
machine-readable descriptions at the link level. it seems to me that 
these may be worth distinguishing so that clients can choose which one 
to follow, but that's a matter of taste and debate, i guess.

**Comment by asbjornu** [comment]
I see. But with a `type` attribute of sorts in the format using the `service` relation or through content negotiation, the `service` relation would provide the same semantics, agree? Having an API serve human readable HTML to browsers and `application/ld+json` to clients who `Accept` it is becoming more and more common and what I would consider a best practice. Isn't this something we should encourage?

**Comment by dret** [comment]
On 2016-02-24 21:46 , Asbjørn Ulsberg wrote:
> I see. But with a |type| attribute of sorts in the format using the
> |service| relation or through content negotiation, the |service|
> relation would provide the same semantics, agree?

not really, because it's less specific. that's if you mean a type that 
indicates the media type, ie some kind of target hint.

https://github.com/dret/hyperpedia/blob/master/concepts.md#target-resource-hints

you would need to know all media types used for documentation and 
description in order to determine at the link level which one is used 
for what. not an easy thing to do.

> Having an API serve
> human readable HTML to browsers and |application/ld+json| to clients who
> |Accept| it is becoming more and more common and what I would consider a
> best practice. Isn't this something we should encourage?

if you choose to server documentation and description at the same URI, 
then supporting conneg is a good idea. if you choose to treat 
documentation and description as different resources, then those still 
could support conneg (serve documentation as PDF and HTML, for example), 
so the general pattern still applies.

people are experimenting with weaving documentation and description 
together, and that's interesting and may catch on. what i see in 
practice, though, is that if there is human-oriented documentation, it 
often still is good old PDF or HTML, and if there is machine-oriented 
description, it often is not great for somebody looking for a document 
they can just read.

**Comment by asbjornu** [comment]
> people are experimenting with weaving documentation and description together, and that's interesting and may catch on.

I think that's the natural way forward. JSON-LD and everything built with it is pushing people in this direction, so I think it's wise for other technologies to do the same.

> what i see in practice, though, is that if there is human-oriented documentation, it often still is good old PDF or HTML, and if there is machine-oriented description, it often is not great for somebody looking for a document they can just read.

That's indeed how it's been so far, but I believe it's changing. Noticing these patterns and taking advantage of them, pushing in the same direction, is important to do in specifications that will live for many years and have the power to shape the future.

Therefore, I believe that cementing the current behaviour of publishing human-oriented documentation disconnected from the API documentation is a mistake.

**Comment by serialseb** [comment]
FYI for anyone reading through, drafts of json-ld did use describedBy until it was changed to something more specific after the conversation linked above.

**Comment by dret** [comment]
On 2016-02-26 11:57 , Asbjørn Ulsberg wrote:
>     what i see in practice, though, is that if there is human-oriented
>     documentation, it often still is good old PDF or HTML, and if there
>     is machine-oriented description, it often is not great for somebody
>     looking for a document they can just read.
> That's indeed how it's been so far, but I believe it's changing.

it's changing for the low-level tech stuff, and that's good. writing 
PDFs about APIs is very ineffective, and people start feeling the pain 
of shorter release cycles. for those API details, generated docs from 
machine-oriented descriptions are good.

but for the longer-lasting bigger picture, i haven't seen anything that 
even attempts to document the "bigger API picture", puts it into the 
context of the company, other services, and who knows what. if people go 
through the effort of creating this kind of documentation (not all do, 
because it's hard to get right), it's extremely valuable for people to 
get started and understand the big picture. and i definitely have never 
seen (and also have a hard time even imagining) how this kind of 
documentation can be generated from machine-readable API descriptions.

> Therefore, I believe that cementing the current behaviour of publishing
> human-oriented documentation disconnected from the API documentation is
> a mistake.

it's more giving people the option to do both. as mentioned above, 
afaict from the API landscape that we have and how it is evolving, 
documentation and description will remain complementary.

**Comment by dret** [comment]
it seems that this issue converged to #33, meaning that the question is not so much about `describedBy` anymore, but about `service` and `service-desc`. if that's correct, can we close this issue and head over to #33 and resolve things over there? thanks!

**Comment by dret** [comment]
assuming this indeed can be closed and the focus can be on #33, as suggested in the last comment.
