### ISSUE TITLE
How to handle rel="rel1 rel2"

### ISSUE THREAD

**Issue by hvdsomp** [dret/I-D#73]
The serialization of RFC5899bis supports the following shortcut:

`<http://example.org/>;rel="start http://example.net/relation/other"` 

to represent these two links:

 `<http://example.org/>; rel="start", <http://example.org/>; rel="http://example.net/relation/other"`

We need to decide whether to support this shortcut functionality in the JSON serialization too. In the version of the I-D that is currently in Github it is not supported. Language will need to be changed if we decide to support.

**Comment by dret** [comment]
i would argue that your two examples are actually different: one is one link that has two relation types; the other one are two links each having one relation type. depending on the link model that you have, these things might be different. reading carefully through @mnot's latest https://tools.ietf.org/html/draft-nottingham-rfc5988bis-07, i am not entirely sure which way the abstract model leans, but it may lean towards links only having one relation type and then indeed in your example a multi-value `rel` is actually a shortcut for defining multiple links (if that's the case, then https://tools.ietf.org/html/draft-nottingham-rfc5988bis-07#section-3.3 probably should make that explicit).
i am inclined to allow the shortcut syntax in JSON because it also seems to show up in other syntaxes, not just in the native RFC5988bis syntax.

**Comment by dret** [comment]
i have raised https://github.com/mnot/I-D/issues/245 to get @mnot's feedback about this. it does not really change the options that we have, but it does change the way how we have to write about the solution that we choose.

**Comment by dret** [comment]
this case is similar to #71 because we should decide based on attribute semantics. this case is slightly different though because the native syntax does not allow repeating `rel`, but instead allows repeating values within `rel` (it's exactly the other way around in `hreflang`). effectively, that's the same thing (allowing annotation of a link with multiple values of the same target attribute), and the difference in the native syntax is mostly for historical reasons.

**Comment by dret** [comment]
given that `rel="x y"` are indeed two links, the choices here are to support some representation of this in the JSON syntax (microsyntax or array), or to disallow this and require the "flattening" of the shortcut into two different links. my favorite would be to support a shortcut, and to support it in a way that is structurally consistent with `hreflang` (#71).

**Comment by dret** [comment]
suggested resolution for this topic (based on the general pattern proposed as resolution for #74):

- `rel` is represents repeatable values and thus is represented as an array.

- when starting from the native syntax, `rel` values MUST be parsed into whitespace-separated tokens and MUST NOT be copied 1:1 into `rel` members of the link object.

- `rel` always MUST be an array.

- each `rel` token that was produced during tokenization of the whitespace-separated native syntax is represented by one string in the value array.

native: `<http://example.org/>; rel="start";`
JSON: `[ { "href":"http://example.org/", "rel":[ "start" ]} ]`

native: `<http://example.org/>; rel="start home";`
JSON: `[ { "href":"http://example.org/", "rel":["start", "home" ] } ]`

**Comment by hvdsomp** [comment]
Total endorsement in light of the overall solution proposed in #74
